project:
  type: website
  output-dir: docs

website:
  title: "Roberto Olayo"
  navbar:
    background: "#536878"
    left:
      - text: Projects
        href: projects.qmd
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "© 2023 personal website. Powered by <a href='https://quarto.org/'>Quarto</a>."
    right:
      - icon: github
        href: https://github.com/rolayoalarcon
      - icon: twitter
        href: https://twitter.com/Scietwas
    background: "#536878"

format:
  html:
    theme: flatly
    toc: true
